import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDown, ArrowRight } from 'lucide-react';
import { SafeImage } from '@/components/SafeImage';
import { categories, journals, products, socialImages } from '@/data/atelier';
import { MiniSignup, ProductGrid } from '@/components/store/Shell';
import { MotionReveal, MotionItem } from '@/components/MotionReveal';
import { PhotoGrid } from '@/components/PhotoGrid';

function CampaignHero(){return <section className="campaign-hero on-media"><SafeImage src="/assets/frunza-campaign-hero.webp" alt="Frunză Atelier campaign in soft evening light"/><div className="hero-scrim"/><div className="hero-copy on-media"><MotionReveal delay={0}><MotionItem><span className="hero-kicker">A study in softness · Autumn / Winter 2026</span></MotionItem><MotionItem><p className="hero-brand">FRUNZĂ ATELIER</p></MotionItem><MotionItem><h1>Romance,<br/>Reimagined.</h1></MotionItem><MotionItem><p>Timeless pieces for modern days.</p></MotionItem><MotionItem><div className="hero-actions"><Link className="button button-on-media" to="/category/new-in">Shop New In <ArrowRight size={14}/></Link><Link className="hero-secondary" to="/collections">Explore Collection</Link></div></MotionItem></MotionReveal></div><a href="#new-in" className="hero-scroll" aria-label="Scroll to new arrivals"><ArrowDown size={15}/><span>Discover the collection</span></a></section>}
function NewArrivals(){return <section id="new-in" className="home-section home-new"><MotionReveal><div className="section-heading"><MotionItem><div><span className="eyebrow">Just arrived</span><h2>New In</h2></div></MotionItem><MotionItem><Link className="text-link" to="/category/new-in">View all new arrivals <ArrowRight size={15}/></Link></MotionItem></div><ProductGrid items={products.filter(p=>p.isNew).slice(0,4).map(p=>p.id)}/></MotionReveal></section>}
function CategoryEdit(){return <section className="home-section category-edit tinted-band"><MotionReveal><div className="section-heading"><MotionItem><div><span className="eyebrow">Pieces for every day</span><h2>Find your feeling</h2></div></MotionItem><MotionItem><p>Familiar shapes, with a little room for wonder.</p></MotionItem></div><div className="category-grid">{categories.map(([name,image],i)=><MotionItem key={name} className={`category-tile-holder category-tile-holder-${i}`}><Link to={`/category/${name.toLowerCase()}`} className={`category-tile category-tile-${i} on-media`}><SafeImage src={image} alt={`${name} collection`} loading="lazy"/><div><span>{name}</span><small>Explore <ArrowRight size={12}/></small></div></Link></MotionItem>)}</div></MotionReveal></section>}
function AutumnStory(){return <section className="autumn-story"><MotionReveal><MotionItem><Link to="/collections/autumn-winter" className="autumn-image on-media"><SafeImage src="/assets/autumn-reverie-campaign.webp" alt="Autumn Reverie campaign: soft layers in a late-season garden" loading="lazy"/><span className="image-stamp">FRUNZĂ · 26</span></Link></MotionItem></MotionReveal><MotionReveal><MotionItem><div className="autumn-copy"><span className="eyebrow">A collection in quiet layers</span><h2>Autumn<br/><i>Reverie</i></h2><p>Soft textures, nostalgic silhouettes and everyday pieces designed to live with you. A thoughtful wardrobe for the first cool morning and the last golden hour.</p><Link className="button button-dark" to="/collections/autumn-winter">Discover the Collection <ArrowRight size={14}/></Link><span className="autumn-note">THE LATE-SEASON EDIT &nbsp; / &nbsp; 01—07</span></div></MotionItem></MotionReveal></section>}
function Loved(){return <section className="home-section loved-section"><MotionReveal><div className="section-heading"><MotionItem><div><span className="eyebrow">Chosen again and again</span><h2>Most Loved</h2></div></MotionItem><MotionItem><Link className="text-link" to="/shop">Shop the edit <ArrowRight size={15}/></Link></MotionItem></div><ProductGrid compact items={['elise-dress','margot-blouse','fleur-cardigan','colette-trousers']}/></MotionReveal></section>}
function JournalPreview(){return <section className="home-section journal-preview tinted-band"><MotionReveal><div className="section-heading"><MotionItem><div><span className="eyebrow">Notes, looks & little discoveries</span><h2>The Frunză Journal</h2></div></MotionItem><MotionItem><Link className="text-link" to="/journal">Visit the journal <ArrowRight size={15}/></Link></MotionItem></div><div className="journal-grid">{journals.slice(0,3).map(([title,cat,image],i)=><MotionItem key={title}><Link to={`/journal/${['the-art-of-everyday-dressing','a-soft-autumn','behind-the-atelier'][i]}`} className="journal-card"><SafeImage src={image} alt={title} loading="lazy"/><span className="eyebrow">{cat}</span><h3>{title}</h3><span className="read-more">Read More <ArrowRight size={13}/></span></Link></MotionItem>)}</div></MotionReveal></section>}
function BrandStory(){const section=useRef<HTMLElement>(null);const [progress,setProgress]=useState(0);useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const rect=section.current?.getBoundingClientRect();if(rect)setProgress(Math.max(0,Math.min(1,(window.innerHeight-rect.top)/(rect.height+window.innerHeight))))})};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);return <section ref={section} className="brand-story"><MotionReveal><MotionItem><div className="brand-story-photo"><SafeImage src="/assets/atelier-brand-story.webp" alt="A quiet atelier moment with fabrics and a thoughtfully styled garment" loading="lazy"/><span className="photo-caption">A small world of considered things</span></div></MotionItem></MotionReveal><MotionReveal><MotionItem><div className="brand-story-copy"><span className="eyebrow">A note from Frunză</span><h2>Made for the<br/>moments <i>in between.</i></h2><p>Frunză Atelier celebrates the quiet beauty of everyday dressing — thoughtful silhouettes, tactile fabrics, nostalgic details and pieces designed to become part of your story.</p><Link className="text-link" to="/about">The Story Behind Frunză <ArrowRight size={15}/></Link><div className="story-mark">F<span>—</span>A</div><div className="story-notes"><article><span>01 / Silhouette</span><p>Soft lines, familiar shapes and room to move through the day.</p></article><article><span>02 / Texture</span><p>Cotton, fine knits and tactile details bring a little depth.</p></article><article><span>03 / Your own rhythm</span><p>Pieces to return to, style your way and make part of your story.</p></article></div></div></MotionItem></MotionReveal><div className="story-progress" role="progressbar" aria-label="Atelier story progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress*100)}><span style={{transform:`scaleY(${progress})`}}/></div></section>}
function Newsletter(){return <section className="newsletter"><MotionReveal><MotionItem><div><span className="eyebrow">Letters, occasionally</span><h2>Stay in the Atelier</h2><p>Receive first access to new collections, quiet edits, stories and special releases.</p></div></MotionItem></MotionReveal><MotionReveal><MotionItem><div className="newsletter-form"><MiniSignup/><span>Thoughtful notes only. Leave whenever you like.</span></div></MotionItem></MotionReveal></section>}
function SocialEdit(){return <section className="social-edit"><MotionReveal><MotionItem><div className="social-title"><span className="eyebrow">A little life around the clothes</span><h2>Follow the Frunză world</h2><a href="#instagram">@frunza.atelier <ArrowRight size={13}/></a></div></MotionItem><PhotoGrid items={socialImages.map((src,i)=>({src,alt:['A model entering a quiet atelier','Silk scarf on a wooden stool','A dress among garden foliage','Fabric and paper patterns','A close knit detail','Relaxed courtyard tailoring','Garments on a studio rail'][i]}))} className="social-grid"/></MotionReveal></section>}
export default function Index(){return <main><CampaignHero/><NewArrivals/><CategoryEdit/><AutumnStory/><Loved/><JournalPreview/><BrandStory/><Newsletter/><SocialEdit/></main>}
