import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, SlidersHorizontal } from 'lucide-react';
import { categories, collections, money, products } from '@/data/atelier';
import { PageIntro, ProductGrid } from '@/components/store/Shell';
import { SafeImage } from '@/components/SafeImage';

function Catalog({title='Shop',category,description}:{title?:string;category?:string;description?:string}){
 const [size,setSize]=useState('All sizes');const [color,setColor]=useState('All colors');const [collection,setCollection]=useState('All collections');const [categoryFilter,setCategoryFilter]=useState('All categories');const [availability,setAvailability]=useState('All pieces');const [sort,setSort]=useState('Featured');const [maxPrice,setMaxPrice]=useState(250);const [mobileFilters,setMobileFilters]=useState(false);
 const filtered=useMemo(()=>{let list=products.filter(p=>(!category||category==='Clothing'||p.category.toLowerCase()===category.toLowerCase()||(category==='New In'&&p.isNew)||(category==='Sale'&&p.sale))&&p.price<=maxPrice&&(size==='All sizes'||p.sizes.includes(size))&&(color==='All colors'||p.color===color)&&(collection==='All collections'||p.collection===collection)&&(categoryFilter==='All categories'||p.category===categoryFilter)&&availability!=='Out of stock');if(sort==='Newest')list=[...list].sort((a,b)=>Number(b.isNew)-Number(a.isNew));if(sort==='Price: Low to High')list=[...list].sort((a,b)=>a.price-b.price);if(sort==='Price: High to Low')list=[...list].sort((a,b)=>b.price-a.price);if(sort==='Best Selling'){const rank=['elise-dress','margot-blouse','fleur-cardigan','colette-trousers'];list=[...list].sort((a,b)=>(rank.indexOf(a.id)<0?99:rank.indexOf(a.id))-(rank.indexOf(b.id)<0?99:rank.indexOf(b.id)))}return list},[category,size,color,collection,categoryFilter,availability,sort,maxPrice]);
 const clear=()=>{setSize('All sizes');setColor('All colors');setCollection('All collections');setCategoryFilter('All categories');setAvailability('All pieces');setMaxPrice(250)};
 const options=<><label>Category<select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}>{['All categories','Dresses','Tops','Bottoms','Knitwear','Outerwear','Accessories'].map(x=><option key={x}>{x}</option>)}</select></label><label>Size<select value={size} onChange={e=>setSize(e.target.value)}>{['All sizes','XS','S','M','L','XL'].map(x=><option key={x}>{x}</option>)}</select></label><label>Color<select value={color} onChange={e=>setColor(e.target.value)}>{['All colors',...Array.from(new Set(products.map(p=>p.color)))].map(x=><option key={x}>{x}</option>)}</select></label><label>Collection<select value={collection} onChange={e=>setCollection(e.target.value)}>{['All collections',...Array.from(new Set(products.map(p=>p.collection)))].map(x=><option key={x}>{x}</option>)}</select></label><label className="range-filter">Price up to {money(maxPrice)}<input type="range" min="50" max="250" step="5" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label><label>Availability<select value={availability} onChange={e=>setAvailability(e.target.value)}><option>All pieces</option><option>In stock</option><option>Out of stock</option></select></label></>;
 return <main className="catalog-page"><PageIntro crumb={title} title={title} description={description||'Considered pieces for a wardrobe that feels like your own. Explore familiar shapes, tactile fabrics and small details worth keeping.'}/>{category&&<div className="catalog-banner on-media">{categories.find(([x])=>x.toLowerCase()===category.toLowerCase())&&<SafeImage src={categories.find(([x])=>x.toLowerCase()===category.toLowerCase())![1]} alt={`${category} editorial`} loading="lazy"/>}<span>A quiet edit of {title.toLowerCase()}</span></div>}<section className="catalog-layout"><aside className={`filter-sidebar ${mobileFilters?'filters-open':''}`}><div className="filter-title"><span className="eyebrow">Refine the edit</span><button onClick={clear}>Clear</button></div><div className="filter-group"><span className="eyebrow">Shop categories</span>{['New In','Dresses','Tops','Bottoms','Knitwear','Outerwear','Accessories','Sale'].map(x=><Link key={x} to={`/category/${x.toLowerCase().split(' ').join('-')}`}>{x}</Link>)}</div>{options}<div className="filter-group"><span className="eyebrow">Shop all</span><Link to="/collections">Browse collections <ArrowRight size={13}/></Link></div></aside><div className="catalog-products"><div className="catalog-tools"><span>{filtered.length} {filtered.length===1?'piece':'pieces'}</span><button className="filter-mobile" onClick={()=>setMobileFilters(!mobileFilters)}><SlidersHorizontal size={14}/> Filters</button><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}>{['Featured','Newest','Price: Low to High','Price: High to Low','Best Selling'].map(x=><option key={x}>{x}</option>)}</select></label></div>{filtered.length?<ProductGrid items={filtered.map(p=>p.id)}/>:<div className="no-results"><h2>Nothing in this edit just yet.</h2><p>Try another size, shade or collection.</p><button className="button button-light" onClick={clear}>Clear filters</button></div>}</div></section></main>
}
export function ShopPage(){return <Catalog title="Shop"/>}
export function CategoryPage(){const {slug=''}=useParams();const title=slug.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');const description=title==='Sale'?'A small selection of past-season favourites, considered again.':'A considered selection of '+title.toLowerCase()+' for everyday dressing.';return <Catalog title={title} category={title} description={description}/>}
export function CollectionsPage(){const {slug}=useParams();if(!slug)return <main className="collections-page"><PageIntro crumb="Collections" title="Collections" description="A wardrobe considered in chapters, each with its own little mood."/><div className="collection-grid">{collections.map(([title,id,image],i)=><Link className={`collection-tile collection-tile-${i} on-media`} key={id} to={`/collections/${id}`}><SafeImage src={image} alt={`${title} collection campaign`} loading="lazy"/><div><span className="eyebrow">The Frunză collection</span><h2>{title}</h2><span className="text-link">Discover the edit <ArrowRight size={14}/></span></div></Link>)}</div></main>;const c=collections.find(x=>x[1]===slug);if(!c)return <Catalog title="Shop"/>;const featured=products.filter(p=>p.collection===c[0]);return <main><div className="collection-detail-hero on-media"><SafeImage src={c[2]} alt={`${c[0]} fashion collection`} loading="eager"/><div><span className="eyebrow">A Frunză collection</span><h1>{c[0]}</h1><p>A thoughtful chapter in the Frunză wardrobe — familiar shapes, tactile detail and pieces to wear your own way.</p><Link to="/shop" className="button button-light">Shop the collection <ArrowRight size={14}/></Link></div></div><section className="home-section"><div className="section-heading"><div><span className="eyebrow">Selected pieces</span><h2>In this collection</h2></div></div><ProductGrid items={featured.length?featured.map(p=>p.id):products.slice(0,4).map(p=>p.id)}/></section></main>}
